[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchorpresale = "4rucZkUgtAGLjPsiTtTepa3pGcZtPs43Q11BsYi4wRF7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/aliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
